version: "3.7"

services:
  osrm-backend:
    image: osrm/osrm-backend:v5.22.0
    environment:
      FILE_NAME: data
      OSRM_VERSION: v5.22.0
      TAR_DIRECTORY: data.tar.gz
      DOWNLOAD_URL: https://s3.eu-north-1.amazonaws.com/pm-mapbox-test.iteam.se
    volumes:
      - ./data:/data
    ports:
      - 5000:5000
    command:
      - bash
      - -c
      - |
        # install dependencies
        if [[ ! -f "/data/$${FILE_NAME}.osrm" ]]; then
          # check if tar-directory exists
          if [[ ! -f "/data/$${TAR_DIRECTORY}" ]]; then
            # check if wget exists, else install
            if [[ ! $$(command -v wget) ]]; then
              apt-get update
              apt-get install -y --no-install-recommends wget
              rm -rf /var/lib/apt/lists/*
            fi
            # certificates takes space, ignore them
            wget --no-check-certificate --debug "$${DOWNLOAD_URL}/$${OSRM_VERSION}/$${TAR_DIRECTORY}" -O "/data/$${TAR_DIRECTORY}"
          fi
          # extract pre-compiled data to /data
          tar -C / -xvf "/data/$${TAR_DIRECTORY}"
          # remove tar-directory, since it takes space
          rm -rf "/data/$${TAR_DIRECTORY}"
        fi
        # start application using extracted data in directory /data
        osrm-routed --algorithm mld "/data/$${FILE_NAME}.osrm"
  redis:
    image: redis:5-stretch
    ports:
      - 6379:6379
