# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - postgres.yaml
  - rabbitmq.yaml
  - redis.yaml
  - minio.yaml

# namespace to deploy all Resources to
namespace: predictivemovement-dev
