name: Integration tests

on: [pull_request]

jobs:
  build-and-push-route-optimization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build route-optimization-image
        run: docker build packages/route-optimization-jsprit --tag iteam1337/pm-route-optimization-jsprit:latest
      - name: Push route-optimization-image
        run: docker push iteam1337/pm-route-optimization-jsprit:latest
  run-integration-tests:
    needs: build-and-push-route-optimization
    env:
      AMQP_HOST: localhost
    defaults:
      run:
        working-directory: packages/engine_umbrella/
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      route-optmization-jsprit:
        image: iteam1337/pm-route-optimization-jsprit
        env:
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: "5672"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 23
          elixir-version: 1.11.1
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: create database
        run: mix do event_store.create, event_store.init
      - name: Run tests
        run: mix test
